server:
  port: 8083
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs/
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuixingchen/springclouddemo.git
          searchPaths: baseconfigrepo
