server:
  port: 8081
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs/
spring:
  http:
    encoding: #HttpEncodingAutoConfiguration配置编码过滤器HttpEncodingProperties
      force: true