server:
  port: 8087
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/