server:
  port: 8084
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs/


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/