server:
  port: 8087
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/logs/

spring:
  mvc:
    view:
      prefix: classpath:/resources/templates/
      suffix: .html

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/